name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        id: cache-node
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
      - uses: changesets/action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          publish: pnpm changeset publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
