name: Format

on:
  # Disabled because branch protections rules don't allow pushes to main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run format
      - uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[ci] format"
          branch: ${{ github.head_ref }}
          commit_author: ${{ github.event.commits[0].author.name }} <${{ github.actor }}@users.noreply.github.com>

